const DesignActionTypes = {
    TOGGLE_AUTH_COMPONENT: 'TOGGLE_AUTH_COMPONENT',
    SWITCH_AUTH_COMPONENT: 'SWITCH_AUTH_COMPONENT',
    TOGGLE_SHOP_CARD: "TOGGLE_SHOP_CARD",

    REDIRECT_TO_CHECKOUT : "REDIRECT_TO_CHECKOUT",
};

export default DesignActionTypes;
