const SubCategoriesTypes = {

    FETCH_ALL_SUB_CATEGORIES_START: 'FETCH_ALL_SUB_CATEGORIES_START',
    FETCH_ALL_SUB_CATEGORIES_SUCCESS: 'FETCH_ALL_SUB_CATEGORIES_SUCCESS',
    FETCH_ALL_SUB_CATEGORIES_FAILURE: 'FETCH_ALL_SUB_CATEGORIES_FAILURE',

    GET_SUB_CATEGORY_START: 'GET_SUB_CATEGORY_START',
    GET_SUB_CATEGORY_SUCCESS: 'GET_SUB_CATEGORY_SUCCESS',
    GET_SUB_CATEGORY_FAILURE: 'GET_SUB_CATEGORY_FAILURE',
};

export default SubCategoriesTypes;
