const DeliveryActionTypes = {
    RETRIEVE_THE_WILAYA_DETAILS_START: ' RETRIEVE_THE_WILAYA_DETAILS_START',
    RETRIEVE_THE_WILAYA_DETAILS_SUCCESS: ' RETRIEVE_THE_WILAYA_DETAILS_SUCCESS',
    RETRIEVE_THE_WILAYA_DETAILS_FAILURE: ' RETRIEVE_THE_WILAYA_DETAILS_FAILURE',
}
export default DeliveryActionTypes;