const GroupsActionTypes = {
    FETCH_ALL_GROUPS_START: 'FETCH_ALL_GROUPS_START',
    FETCH_ALL_GROUPS_SUCCESS: 'FETCH_ALL_GROUPS_SUCCESS',
    FETCH_ALL_GROUPS_FAILURE: 'FETCH_ALL_GROUPS_FAILURE',

    GET_GROUP_START: 'GET_GROUP_START',
    GET_GROUP_SUCCESS: 'GET_GROUP_SUCCESS',
    GET_GROUP_FAILURE: 'GET_GROUP_FAILURE',
}

export default GroupsActionTypes;