const AuthActionTypes = {
    //sign up
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',

    //sign in
    SIGN_IN_START : "SIGN_IN_START",
    SIGN_IN_SUCCESS : "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE : "SIGN_IN_FAILURE",

    //check the user
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',

    //sign out
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

    //forget password
    SEND_FORGET_PASSWORD_EMAIL_START: 'SEND_FORGET_PASSWORD_EMAIL_START',
    SEND_FORGET_PASSWORD_EMAIL_SUCCESS: 'SEND_FORGET_PASSWORD_EMAIL_SUCCESS',
    SEND_FORGET_PASSWORD_EMAIL_FAILURE: 'SEND_FORGET_PASSWORD_EMAIL_FAILURE',

    //reset password
    RESET_PASSWORD_START: 'RESET_PASSWORD_START',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

    //update user information
    UPDATE_PROFILE_INFORMATION_START: 'UPDATE_PROFILE_INFORMATION_START',
    UPDATE_PROFILE_INFORMATION_SUCCESS: 'UPDATE_PROFILE_INFORMATION_SUCCESS',
    UPDATE_PROFILE_INFORMATION_FAILURE: 'UPDATE_PROFILE_INFORMATION_FAILURE',

};

export default AuthActionTypes;
