const ProductsActionTypes = {
    FETCH_ALL_PRODUCTS_START: 'FETCH_ALL_PRODUCTS_START',
    FETCH_ALL_PRODUCTS_SUCCESS: 'FETCH_ALL_PRODUCTS_SUCCESS',
    FETCH_ALL_PRODUCTS_FAILURE: 'FETCH_ALL_PRODUCTS_FAILURE',

    FETCH_PRODUCTS_BY_CATEGORY_START: 'FETCH_PRODUCTS_BY_CATEGORY_START',
    FETCH_PRODUCTS_BY_CATEGORY_SUCCESS: 'FETCH_PRODUCTS_BY_CATEGORY_SUCCESS',
    FETCH_PRODUCTS_BY_CATEGORY_FAILURE: 'FETCH_PRODUCTS_BY_CATEGORY_FAILURE',

    FETCH_PRODUCTS_BY_SUB_CATEGORY_START: 'FETCH_PRODUCTS_BY_SUB_CATEGORY_START',
    FETCH_PRODUCTS_BY_SUB_CATEGORY_SUCCESS: 'FETCH_PRODUCTS_BY_SUB_CATEGORY_SUCCESS',
    FETCH_PRODUCTS_BY_SUB_CATEGORY_FAILURE: 'FETCH_PRODUCTS_BY_SUB_CATEGORY_FAILURE',

    FETCH_PRODUCTS_BY_STORE_START: 'FETCH_PRODUCTS_BY_STORE_START',
    FETCH_PRODUCTS_BY_STORE_SUCCESS: 'FETCH_PRODUCTS_BY_STORE_SUCCESS',
    FETCH_PRODUCTS_BY_STORE_FAILURE: 'FETCH_PRODUCTS_BY_STORE_FAILURE',

    GET_PRODUCT_START: 'GET_PRODUCT_START',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE: 'GET_PRODUCT_FAILURE',
}

export default ProductsActionTypes;