const CategoriesActionTypes = {

    FETCH_ALL_CATEGORIES_START: 'FETCH_ALL_CATEGORIES_START',
    FETCH_ALL_CATEGORIES_SUCCESS: 'FETCH_ALL_CATEGORIES_SUCCESS',
    FETCH_ALL_CATEGORIES_FAILURE: 'FETCH_ALL_CATEGORIES_FAILURE',

    GET_CATEGORY_START: 'GET_CATEGORY_START',
    GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
    GET_CATEGORY_FAILURE: 'GET_CATEGORY_FAILURE',
}

export default CategoriesActionTypes;