const StoresActionTypes = {

    FETCH_ALL_STORES_START: 'FETCH_ALL_STORES_START',
    FETCH_ALL_STORES_SUCCESS: 'FETCH_ALL_STORES_SUCCESS',
    FETCH_ALL_STORES_FAILURE: 'FETCH_ALL_STORES_FAILURE',

    GET_STORE_START: 'GET_STORE_START',
    GET_STORE_SUCCESS: 'GET_STORE_SUCCESS',
    GET_STORE_FAILURE: 'GET_STORE_FAILURE',
};

export default StoresActionTypes;
