const OrdersActionTypes = {

    FETCH_ALL_ORDERS_START: 'FETCH_ALL_ORDERS_START',
    FETCH_ALL_ORDERS_SUCCESS: 'FETCH_ALL_ORDERS_SUCCESS',
    FETCH_ALL_ORDERS_FAILURE: 'FETCH_ALL_ORDERS_FAILURE',

    GET_ORDER_START: 'GET_ORDER_START',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',

    ADD_ORDER_START: 'ADD_ORDER_START',
    ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
    ADD_ORDER_FAILURE: 'ADD_ORDER_FAILURE',

    UPDATE_ORDER_START: 'UPDATE_ORDER_START',
    UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS',
    UPDATE_ORDER_FAILURE: 'UPDATE_ORDER_FAILURE',

    DELETE_ORDER_START: 'DELETE_ORDER_START',
    DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
    DELETE_ORDER_FAILURE: 'DELETE_ORDER_FAILURE',
};

export default OrdersActionTypes;
